Add _GLFW_X11 define to fix linux compilation error
Since raylib updated to GLFW 3.4, rglfw.c has been failing to compile
with the error:

src/rglfw.c:57:10: error: #error "Cannot disable Wayland and X11 at the same time"
   57 |         #error "Cannot disable Wayland and X11 at the same time"
      |          ^~~~~

Adding a define for `_GLFW_X11` fixes it. GLFW 3.4 also "unified" glfw,
there is no more separate "glfw-x11" and "glfw-wayland" build.
Currently, game-premake does not support building like this, further
research is required.